services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - .:/app
      # Exclude the virtual environment from the mount
      - /app/.venv
    working_dir: /app
    ports:
      - "8000:8000"
    networks:
      - botnet

  telegram_bot:
    build:
      context: .
      dockerfile: telegram_bot/Dockerfile.telegram
    volumes:
      - .:/app
      # Exclude the virtual environment from the mount
      - /app/.venv
    working_dir: /app
    environment:
      - API_BASE_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - botnet

networks:
  botnet:
    driver: bridge