FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY pyproject.toml ./
COPY uv.lock ./
RUN pip3 install uv --break-system-packages
RUN uv sync
RUN uv add uvicorn

EXPOSE 8000

COPY . .
RUN rm -rf /app/telegram_bot

CMD ["uv","run","main.py"]
