
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ../pyproject.toml pyproject.toml
COPY ../uv.lock uv.lock
COPY ../ .

# Remove any existing .venv directory that might be corrupted
RUN rm -rf .venv

RUN pip3 install uv --break-system-packages
RUN uv sync

CMD ["uv", "run", "telegram_bot/bot.py"]